clean_txt_files:
	find . -type f -name '*.glob' -exec rm {} +
	find . -type f -name '*.vo' -exec rm {} +
	find . -type f -name '*.vok' -exec rm {} +
	find . -type f -name '*.vos' -exec rm {} +
clean: clean_txt_files
